# 应用名称
spring:
  application:
    name: springboot-study-core
  datasource:
    url: jdbc:mysql://uninut.top:3306/study?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Chen265.
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.MySQL57Dialect
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
server:
  port: 9090
